### PR TITLE
Create Docker Images and Releases

### PR DESCRIPTION
**Pull request by lswith**
Hey mate,
I don't want to maintain this codebase I just wanted to set up releases and Docker containers so that it could be deployable from github. 

I've added a lot of stuff here that works only for my repository but I am happy to PM and give you the low down on how to set it up for your repo. I've also renamed the repository to match the current prometheus convention and added a vendor directory as well.

### CODE REVIEW

**Comment by jonnenauha** [comment]
I can't merge this. You changed the repo name (this won't transfer in a PR ofc), all the docker/ci config files point to your repo (absolute URLS).

I appreciate the work, but why is it so complex? You could have made a simple docker file that I could use with minimal changes.

Using promu afaik not mandated by prometheus (so they list my exporter on their pages). What is the benefit compared to using `go` commands and my simple script, does it auto-build the docker images or something? Makefiles has always looked a bit weird to me in go repos. Looks like its there to wrap promu.

The circle-ci thing could have gone to a different PR, looks like a separate feature all together.

In total this is just has a lot of stuff for docker support :) You are the second person asking for docker support, so I will implement it at some point. This PR will help me out when I do, but again, I can't merge this as is.

**Comment by lswith** [comment]
Yeah that's fair. One thing that I realised after this PR is making sure to
build for multiple versions of varnish. Currently it only builds for
varnish 4.1

**Comment by jonnenauha** [comment]
You might have noticed the commit there. I realized this service cant run in a docker container. Well, it can but the varnish instance must be running in the same docker container. I think this is something most people would not like to do, me controlling the varnish instance.

I saw you install varnish to the docker image here https://github.com/lswith/varnish_exporter/blob/master/Dockerfile#L6-L13
You will get the needed cmdline tools but the varnishstat will only report for the instance inside the container. If the varnish is running on the host or in another container, you wont get your stats.

I haven't found a way to (easily at least) query varnish stats without the varnishstat tool. So that we could come out of the container into the host system (--net=host etc.) and pull in the data.

I did make the test + build + release system with travis-ci, thanks for the inspiration on that :) 

There is no need to build different versions of varnish. It might be nice to get test scrapes out of 3.x, 4.x and 5.x at some point in the CI pipeline, to validate it parses ok. I did plan to make the test env load some actualy VLCs, run traffic in and then do scrapes.

I haven't done anything for 5.x support yet. I suspect there wont be major issues if they havent changed the output format of varnishstat -j (I would be suprised).

**Comment by lswith** [comment]
it does work in a docker container as long as you have access to the _.vsm file. Also I've tried using varnishstat 4.1 with multiple versions of varnish (4, 41, 5) and it seems to work as expected.

**Comment by jonnenauha** [comment]
So do you mount the dir from the host where the .vms files are located to the container?

I suppose it could work if we document what the container expects file path to be.

I'm still a bit skeptical how this all works. This file is the only way to communicate with the host, am I to understand that the stats are written as a binary stream of something to this file? What is the exact line you use to run the docker image?

**Comment by lswith** [comment]
the _.vsm file is usually located in /var/lib/varnish/{hostname}/. The {hostname} can be set with using the `-n` parameter in varnishd. 

the exact line to use with the docker file is:
`docker run -d -p 9131:9131 -v /var/lib/varnish:/var/lib/varnish lswith/varnish-exporter -N /var/lib/varnish/default/_.vsm` 
assuming my varnishd configuration was used with `-n default`.

**Pull request closed without merging**
